---
- name: Install MariaDB
  hosts: db
  tasks:
  - name: Update system packages
    apt:
      name: '*'
      state: latest

  - name: Install MariaDB packages
    apt:
      name: mariadb-server
      state: present
      update_cache: yes
    become: yes
